"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 150

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - FL_shoulder_servo
          - FL_femur_servo
          - FL_tibia_servo
          - FR_shoulder_servo
          - FR_femur_servo
          - FR_tibia_servo
          - RL_shoulder_servo
          - RL_femur_servo
          - RL_tibia_servo
          - RR_shoulder_servo
          - RR_femur_servo
          - RR_tibia_servo


      gains:
        FL_shoulder_servo : {p: 180, d: 0.5, i: 20}
        FL_femur_servo :    {p: 180, d: 0.5, i: 20}
        FL_tibia_servo :    {p: 180, d: 0.5, i: 20}
        FR_shoulder_servo : {p: 180, d: 0.5, i: 20}
        FR_femur_servo :    {p: 180, d: 0.5, i: 20}
        FR_tibia_servo :    {p: 180, d: 0.5, i: 20}
        RL_shoulder_servo : {p: 180, d: 0.5, i: 20}
        RL_femur_servo :    {p: 180, d: 0.5, i: 20}
        RL_tibia_servo :    {p: 180, d: 0.5, i: 20}
        RR_shoulder_servo : {p: 180, d: 0.5, i: 20}
        RR_femur_servo :    {p: 180, d: 0.5, i: 20}
        RR_tibia_servo :    {p: 180, d: 0.5, i: 20}
