knee_orientation : "<<"
pantograph_leg : false
odom_scaler: 1.0
max_linear_velocity_x : 0.1
max_linear_velocity_y : 0.10
max_angular_velocity_z : 0.1
com_x_translation : 0.08
swing_height : 0.04
stance_depth : 0.00
stance_duration : 0.4
nominal_height : 0.18
