knee_orientation : ">>"
pantograph_leg : false
odom_scaler: 1.0
max_linear_velocity_x : 0.5
max_linear_velocity_y : 0.25
max_angular_velocity_z : 1.0
com_x_translation : 0.0
swing_height : 0.05000000000000001
stance_depth : 0.010000000000000002
stance_duration : 0.28
nominal_height : 0.16999999999999998