knee_orientation : ">>"
pantograph_leg : false
odom_scaler: 1.0
max_linear_velocity_x : 0.1
max_linear_velocity_y : 0.1
max_angular_velocity_z : 0.25
com_x_translation : -0.075
swing_height : 0.05
stance_depth : 0.01
stance_duration : 0.6
nominal_height : 0.20
