knee_orientation : ">>"
pantograph_leg : false
odom_scaler: 1.0
max_linear_velocity_x : 0.05
max_linear_velocity_y : 0.05
max_angular_velocity_z : 0.25
com_x_translation : -0.085
swing_height : 0.015
stance_depth : 0.01
stance_duration : 1
nominal_height : 0.19
