joint_limits:


    Femur_FR:
      has_position_limits: true
      min_position: 0
      max_position: 120
      has_velocity_limits: false
      max_velocity: 0
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      
    Tibia_FR:
      has_position_limits: true
      min_position: 90
      max_position: 180
      has_velocity_limits: false
      max_velocity: 0
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0