base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS

shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 0.5
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

<<<<<<< HEAD
conservative_reset_dist: 0.05
=======
conservative_reset_dist: 0.1
>>>>>>> 6aab6f32f276a02b6d6a9fa069145de750414a31
