Bear:

    # Publish all joint states
    joints_update:
      type: joint_state_controller/JointStateController
      publish_rate: 10
    
    Femur_FR_PositionController:                                               # Name of the controller
      type: position_controllers/JointPositionController         # Since JointA uses effort interface this controller type is  used      
      joint: Femur_FR                                                                # Name of the joint for which this controller belongs to.
      #pid: {p: 1.0, i: 1.0, d: 1.0}                                    # PID values
    
    Tibia_FR_PositionController:                                             
      type: position_controllers/JointPositionController        # Since JointB uses effort interface this controller type is  used   
      joint: Tibia_FR                                                                 
      #pid: {p: 1.0, i: 1.0, d: 0.0}


      # No PID values defined since this controller simply passes the input position command to the actuators