base: base_link
left_front:
  - FL_shoulder
  - FL_femur
  - FL_tibia
  - FL_foot

right_front:
  - FR_shoulder
  - FR_femur
  - FR_tibia
  - FR_foot

left_hind:
  - RL_shoulder
  - RL_femur
  - RL_tibia
  - RL_foot

right_hind:
  - RR_shoulder
  - RR_femur
  - RR_tibia
  - RR_foot